name: Build and deploy
on: [push]

env:
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  CI: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Yarn Install
        run: yarn

      - name: Yarn Build
        run: yarn build

      - name: 'Upload build'
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build
          retention-days: 1

  develop:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/heads/develop')

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build

      - name: Deploy to Firebase - DEVELOP
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:develop

  production:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/heads/master')

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build

      - name: Deploy to Firebase - PRODUCTION
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:production
